# Generated by Django 2.2.5 on 2019-09-06 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_contains', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_cont', to='shop.Item')),
                ('order_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_item', to='shop.Order')),
            ],
        ),
    ]
