# Generated by Django 2.2.5 on 2019-09-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190908_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
